;
; File generated by cc65 v 2.15 - Git 60958f0
;
	.fopt		compiler,"cc65 v 2.15 - Git 60958f0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_itoa
	.export		___ppu_str
	.export		___write_string
	.export		___write_fmtstring

.segment	"BSS"

___ppu_str:
	.res	2,$00
__s:
	.res	2,$00
_cbuff:
	.res	6,$00
_args:
	.res	2,$00

; ---------------------------------------------------------------
; void __near__ __fastcall__ __write_string (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	___write_string: near

.segment	"CODE"

	jmp     L0006
L0004:	lda     ___ppu_str
	sta     ptr1
	lda     ___ppu_str+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     $2007
	inc     ___ppu_str
	bne     L0006
	inc     ___ppu_str+1
L0006:	lda     ___ppu_str
	sta     ptr1
	lda     ___ppu_str+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	bne     L0004
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ __write_fmtstring (__near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	___write_fmtstring: near

.segment	"CODE"

	jsr     enter
	ldy     #$00
	lda     (sp),y
	jsr     leaa0sp
	jsr     decax1
	sta     _args
	stx     _args+1
	jmp     L0063
L0060:	lda     (sp),y
	jsr     leaa0sp
	jsr     decax1
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$25
	beq     L0061
	lda     (sp),y
	jsr     leaa0sp
	jsr     decax1
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	jmp     L0064
L0061:	lda     (sp),y
	jsr     leaa0sp
	jsr     decax1
	jsr     pushax
	jsr     ldaxi
	jsr     incax1
	ldy     #$00
	jsr     staxspidx
	lda     (sp),y
	jsr     leaa0sp
	jsr     decax1
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$63
	jeq     L0052
	cmp     #$69
	beq     L0024
	cmp     #$73
	beq     L003D
	jmp     L0062
L0024:	lda     _args
	sec
	sbc     #$02
	sta     _args
	bcs     L002C
	dec     _args+1
L002C:	ldx     _args+1
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jsr     pusha0
	lda     #<(_cbuff)
	ldx     #>(_cbuff)
	jsr     pushax
	ldx     #$00
	lda     #$0A
	jsr     _itoa
	lda     #<(_cbuff)
	sta     __s
	lda     #>(_cbuff)
	sta     __s+1
	jmp     L0033
L0031:	lda     __s
	sta     ptr1
	lda     __s+1
	sta     ptr1+1
	lda     (ptr1),y
	sta     $2007
	inc     __s
	bne     L0033
	inc     __s+1
L0033:	lda     __s
	sta     ptr1
	lda     __s+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	bne     L0031
	jmp     L0062
L003D:	lda     _args
	sec
	sbc     #$02
	sta     _args
	bcs     L0045
	dec     _args+1
L0045:	ldx     _args+1
	jsr     ldaxi
	sta     __s
	stx     __s+1
	jmp     L0048
L0046:	lda     __s
	sta     ptr1
	lda     __s+1
	sta     ptr1+1
	lda     (ptr1),y
	sta     $2007
	inc     __s
	bne     L0048
	inc     __s+1
L0048:	lda     __s
	sta     ptr1
	lda     __s+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	bne     L0046
	jmp     L0062
L0052:	lda     _args
	sec
	sbc     #$02
	sta     _args
	bcs     L005D
	dec     _args+1
L005D:	ldx     _args+1
	sta     ptr1
	stx     ptr1+1
L0064:	lda     (ptr1),y
	sta     $2007
L0062:	lda     (sp),y
	jsr     leaa0sp
	jsr     decax1
	jsr     pushax
	jsr     ldaxi
	jsr     incax1
	ldy     #$00
	jsr     staxspidx
L0063:	lda     (sp),y
	jsr     leaa0sp
	jsr     decax1
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	ldx     #$00
	lda     (ptr1),y
	jne     L0060
	jmp     leave

.endproc

