;
; File generated by cc65 v 2.15 - Git 60958f0
;
	.fopt		compiler,"cc65 v 2.15 - Git 60958f0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_str
	.export		_main

.segment	"DATA"

_str:
	.addr	L0002

.segment	"RODATA"

L0002:
	.byte	$42,$41,$52,$4F,$4E,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     _str
	sta     ptr1
	lda     _str+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     $2007
	lda     _str
	sta     ptr1
	lda     _str+1
	sta     ptr1+1
	iny
	lda     (ptr1),y
	sta     $2007
	lda     _str
	sta     ptr1
	lda     _str+1
	sta     ptr1+1
	iny
	lda     (ptr1),y
	sta     $2007
	rts

.endproc

