;
; File generated by cc65 v 2.15 - Git 60958f0
;
	.fopt		compiler,"cc65 v 2.15 - Git 60958f0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_itoa
	.export		___ppu_str
	.export		___cbuff
	.export		___iskey_pressed_pad1
	.export		___iskey_pressed_pad2
	.export		___wait_key_press_pad1
	.export		___wait_key_press_pad2
	.export		___write_string
	.export		___write_fmtstring

.segment	"BSS"

___ppu_str:
	.res	2,$00
___cbuff:
	.res	6,$00
_args:
	.res	2,$00

; ---------------------------------------------------------------
; int __near__ __fastcall__ __iskey_pressed_pad1 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	___iskey_pressed_pad1: near

.segment	"CODE"

	lda     #$01
	sta     $4016
	lda     #$00
	sta     $4016
	sta     ___cbuff+3
	tax
L00E0:	lda     ___cbuff+3
	cmp     ___cbuff
	txa
	sbc     #$00
	bcs     L00E1
	lda     $4016
	; REMOVED ;
	inc     ___cbuff+3
	jmp     L00E0
L00E1:	lda     $4016
	and     #$01
	beq     L00E3
	lda     #$01
	rts
L00E3:	rts

.endproc

; ---------------------------------------------------------------
; int __near__ __fastcall__ __iskey_pressed_pad2 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	___iskey_pressed_pad2: near

.segment	"CODE"

	lda     #$01
	sta     $4016
	lda     #$00
	sta     $4016
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ __fastcall__ __wait_key_press_pad1 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	___wait_key_press_pad1: near

.segment	"CODE"

L0035:	lda     #$01
	sta     $4016
	lda     #$00
	sta     $4016
	sta     ___cbuff+3
L00E5:	lda     ___cbuff+3
	cmp     #$08
	bcs     L003F
	lda     ___cbuff
	cmp     ___cbuff+3
	bne     L00E6
	lda     $4016
	and     #$01
	beq     L0035
	rts
L00E6:	inc     ___cbuff+3
	jmp     L00E5
L003F:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ __fastcall__ __wait_key_press_pad2 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	___wait_key_press_pad2: near

.segment	"CODE"

L005D:	lda     #$01
	sta     $4016
	lda     #$00
	sta     $4016
	sta     ___cbuff+3
L00E8:	lda     ___cbuff+3
	cmp     #$08
	bcs     L0067
	lda     ___cbuff
	cmp     ___cbuff+3
	bne     L00E9
	lda     $4017
	and     #$01
	beq     L005D
	rts
L00E9:	inc     ___cbuff+3
	jmp     L00E8
L0067:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ __fastcall__ __write_string (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	___write_string: near

.segment	"CODE"

	jmp     L0087
L0085:	lda     ___ppu_str
	sta     ptr1
	lda     ___ppu_str+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     $2007
	inc     ___ppu_str
	bne     L0087
	inc     ___ppu_str+1
L0087:	lda     ___ppu_str
	sta     ptr1
	lda     ___ppu_str+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	bne     L0085
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ __write_fmtstring (__near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	___write_fmtstring: near

.segment	"CODE"

	jsr     enter
	ldy     #$00
	lda     (sp),y
	jsr     leaa0sp
	jsr     decax1
	sta     _args
	stx     _args+1
	jmp     L00EE
L00EB:	lda     (sp),y
	jsr     leaa0sp
	jsr     decax1
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$25
	beq     L00EC
	lda     (sp),y
	jsr     leaa0sp
	jsr     decax1
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	jmp     L00EF
L00EC:	lda     (sp),y
	jsr     leaa0sp
	jsr     decax1
	jsr     pushax
	jsr     ldaxi
	jsr     incax1
	ldy     #$00
	jsr     staxspidx
	lda     (sp),y
	jsr     leaa0sp
	jsr     decax1
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$63
	jeq     L00D3
	cmp     #$69
	beq     L00A5
	cmp     #$73
	beq     L00BE
	jmp     L00ED
L00A5:	lda     _args
	sec
	sbc     #$02
	sta     _args
	bcs     L00AD
	dec     _args+1
L00AD:	ldx     _args+1
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jsr     pusha0
	lda     #<(___cbuff)
	ldx     #>(___cbuff)
	jsr     pushax
	ldx     #$00
	lda     #$0A
	jsr     _itoa
	lda     #<(___cbuff)
	sta     ___ppu_str
	lda     #>(___cbuff)
	sta     ___ppu_str+1
	jmp     L00B4
L00B2:	lda     ___ppu_str
	sta     ptr1
	lda     ___ppu_str+1
	sta     ptr1+1
	lda     (ptr1),y
	sta     $2007
	inc     ___ppu_str
	bne     L00B4
	inc     ___ppu_str+1
L00B4:	lda     ___ppu_str
	sta     ptr1
	lda     ___ppu_str+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	bne     L00B2
	jmp     L00ED
L00BE:	lda     _args
	sec
	sbc     #$02
	sta     _args
	bcs     L00C6
	dec     _args+1
L00C6:	ldx     _args+1
	jsr     ldaxi
	sta     ___ppu_str
	stx     ___ppu_str+1
	jmp     L00C9
L00C7:	lda     ___ppu_str
	sta     ptr1
	lda     ___ppu_str+1
	sta     ptr1+1
	lda     (ptr1),y
	sta     $2007
	inc     ___ppu_str
	bne     L00C9
	inc     ___ppu_str+1
L00C9:	lda     ___ppu_str
	sta     ptr1
	lda     ___ppu_str+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	bne     L00C7
	jmp     L00ED
L00D3:	lda     _args
	sec
	sbc     #$02
	sta     _args
	bcs     L00DE
	dec     _args+1
L00DE:	ldx     _args+1
	sta     ptr1
	stx     ptr1+1
L00EF:	lda     (ptr1),y
	sta     $2007
L00ED:	lda     (sp),y
	jsr     leaa0sp
	jsr     decax1
	jsr     pushax
	jsr     ldaxi
	jsr     incax1
	ldy     #$00
	jsr     staxspidx
L00EE:	lda     (sp),y
	jsr     leaa0sp
	jsr     decax1
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	ldx     #$00
	lda     (ptr1),y
	jne     L00EB
	jmp     leave

.endproc

