;
; File generated by cc65 v 2.15 - Git 60958f0
;
	.fopt		compiler,"cc65 v 2.15 - Git 60958f0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_itoa
	.export		___ppu_str
	.export		___cbuff
	.export		___iskey_pressed_pad1
	.export		___iskey_pressed_pad2
	.export		___wait_key_press_pad1
	.export		___wait_key_press_pad2
	.export		___write_string
	.export		___write_fmtstring
	.export		_loadkey_pad1

.segment	"DATA"

_pad_status:
	.byte	$00
	.byte	$00

.segment	"BSS"

___ppu_str:
	.res	2,$00
___cbuff:
	.res	6,$00
_args:
	.res	2,$00

; ---------------------------------------------------------------
; int __near__ __fastcall__ __iskey_pressed_pad1 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	___iskey_pressed_pad1: near

.segment	"CODE"

	jsr     _loadkey_pad1
	lda     _pad_status
	ldx     #$00
	and     #$01
	beq     L009A
	lda     #$01
	rts
L009A:	rts

.endproc

; ---------------------------------------------------------------
; int __near__ __fastcall__ __iskey_pressed_pad2 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	___iskey_pressed_pad2: near

.segment	"CODE"

	lda     $4017
	ldx     #$00
	and     #$01
	beq     L009C
	lda     #$01
	rts
L009C:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ __fastcall__ __wait_key_press_pad1 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	___wait_key_press_pad1: near

.segment	"CODE"

L003B:	jsr     _loadkey_pad1
	lda     $4016
	and     #$01
	beq     L003B
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ __fastcall__ __wait_key_press_pad2 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	___wait_key_press_pad2: near

.segment	"CODE"

L009D:	lda     $4017
	and     #$01
	beq     L009D
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ __fastcall__ __write_string (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	___write_string: near

.segment	"CODE"

L0054:	lda     ___ppu_str
	ldx     ___ppu_str+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     ___ppu_str
	stx     ___ppu_str+1
	ldy     #$00
	lda     (regsave),y
	sta     $2007
	lda     ___ppu_str
	sta     ptr1
	lda     ___ppu_str+1
	sta     ptr1+1
	lda     (ptr1),y
	bne     L0054
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ __write_fmtstring (__near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	___write_fmtstring: near

.segment	"CODE"

	jsr     enter
	ldy     #$00
	lda     (sp),y
	jsr     leaa0sp
	jsr     decax1
	sta     _args
	stx     _args+1
	jmp     L00A2
L009F:	lda     (sp),y
	jsr     leaa0sp
	jsr     decax1
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$25
	beq     L00A0
	lda     (sp),y
	jsr     leaa0sp
	jsr     decax1
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	jmp     L00A3
L00A0:	lda     (sp),y
	jsr     leaa0sp
	jsr     decax1
	jsr     pushax
	jsr     ldaxi
	jsr     incax1
	ldy     #$00
	jsr     staxspidx
	lda     (sp),y
	jsr     leaa0sp
	jsr     decax1
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$63
	beq     L008C
	cmp     #$69
	beq     L0072
	cmp     #$73
	beq     L0081
	jmp     L00A1
L0072:	lda     _args
	sec
	sbc     #$02
	sta     _args
	bcs     L007A
	dec     _args+1
L007A:	ldx     _args+1
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jsr     pusha0
	lda     #<(___cbuff)
	ldx     #>(___cbuff)
	jsr     pushax
	ldx     #$00
	lda     #$0A
	jsr     _itoa
	lda     #<(___cbuff)
	sta     ___ppu_str
	lda     #>(___cbuff)
	sta     ___ppu_str+1
	jsr     ___write_string
	jmp     L0070
L0081:	lda     _args
	sec
	sbc     #$02
	sta     _args
	bcs     L0089
	dec     _args+1
L0089:	ldx     _args+1
	jsr     ldaxi
	sta     ___ppu_str
	stx     ___ppu_str+1
	jsr     ___write_string
	jmp     L0070
L008C:	lda     _args
	sec
	sbc     #$02
	sta     _args
	bcs     L0097
	dec     _args+1
L0097:	ldx     _args+1
	sta     ptr1
	stx     ptr1+1
L00A3:	lda     (ptr1),y
	sta     $2007
L0070:	ldy     #$00
L00A1:	lda     (sp),y
	jsr     leaa0sp
	jsr     decax1
	jsr     pushax
	jsr     ldaxi
	jsr     incax1
	ldy     #$00
	jsr     staxspidx
L00A2:	lda     (sp),y
	jsr     leaa0sp
	jsr     decax1
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	ldx     #$00
	lda     (ptr1),y
	jne     L009F
	jmp     leave

.endproc

; ---------------------------------------------------------------
; void __near__ __fastcall__ loadkey_pad1 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_loadkey_pad1: near

.segment	"CODE"

	lda     #$01
	sta     $4016
	lda     #$00
	sta     $4016
	sta     ___cbuff+3
	tax
L00A4:	lda     ___cbuff+3
	cmp     ___cbuff
	txa
	sbc     #$00
	bcs     L0011
	lda     $4016
	sta     ___cbuff + 5 ; REMOVE ME ;
	inc     ___cbuff+3
	jmp     L00A4
L0011:	rts

.endproc

