;
; File generated by cc65 v 2.15 - Git ab1600b
;
	.fopt		compiler,"cc65 v 2.15 - Git ab1600b"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_main

.segment	"DATA"

_str:
	.addr	L0001
__count:
	.byte	$00

.segment	"RODATA"

L0001:
	.byte	$48,$45,$4C,$4C,$4F,$5F,$4D,$59,$4C,$49,$42,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jmp     L0007
L0005:	lda     _str
	ldx     _str+1
	ldy     __count
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	sta     $2007
	inc     __count
L0007:	lda     _str
	ldx     _str+1
	ldy     __count
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	bne     L0005
	rts

.endproc

