;
; File generated by cc65 v 2.15 - Git 60958f0
;
	.fopt		compiler,"cc65 v 2.15 - Git 60958f0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_write_string
	.export		_func

.segment	"RODATA"

L0005:
	.byte	$46,$72,$6F,$6D,$20,$74,$32,$2E,$63,$20,$66,$75,$6E,$63,$00

; ---------------------------------------------------------------
; void __near__ __fastcall__ func (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_func: near

.segment	"CODE"

	lda     #$01
	jsr     pusha
	jsr     pusha
	lda     #<(L0005)
	ldx     #>(L0005)
	jmp     _write_string

.endproc

