;
; File generated by cc65 v 2.15 - Git 60958f0
;
	.fopt		compiler,"cc65 v 2.15 - Git 60958f0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_waitvblank
	.import		___ppu_str
	.import		___cbuff
	.import		___iskey_pressed_pad1
	.import		___write_string
	.export		_main

.segment	"DATA"

_linex:
	.byte	$01
_strs:
	.addr	L0007
	.addr	L0009
_colors:
	.byte	$05
	.byte	$09
	.byte	$01

.segment	"RODATA"

L0009:
	.byte	$53,$74,$72,$69,$74,$65,$72,$20,$56,$65,$67,$65,$74,$61,$21,$00
L0007:
	.byte	$53,$74,$72,$69,$74,$65,$72,$20,$41,$6C,$66,$61,$21,$00

.segment	"BSS"

_x:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     _waitvblank
	lda     #$3F
	sta     $2006
	lda     #$00
	sta     $2006
	lda     #$05
	sta     $2007
	lda     #$3F
	sta     $2006
	lda     #$03
	sta     $2006
	lda     #$01
	sta     $2007
	lda     #$00
L0072:	sta     ___cbuff
	jsr     ___iskey_pressed_pad1
	stx     tmp1
	ora     tmp1
	beq     L002E
	lda     #$20
	sta     $2006
	lda     #$41
	sta     $2006
	lda     _strs
	sta     ___ppu_str
	lda     _strs+1
	jmp     L0073
L002E:	lda     #$01
	sta     ___cbuff
	jsr     ___iskey_pressed_pad1
	stx     tmp1
	ora     tmp1
	beq     L0072
	lda     #$20
	sta     $2006
	lda     #$41
	sta     $2006
	lda     _strs+2
	sta     ___ppu_str
	lda     _strs+2+1
L0073:	sta     ___ppu_str+1
	jsr     ___write_string
	lda     #$00
	sta     $2005
	sta     $2005
	lda     #$08
	sta     $2001
L0070:	jmp     L0070

.endproc

