;
; File generated by cc65 v 2.15 - Git 60958f0
;
	.fopt		compiler,"cc65 v 2.15 - Git 60958f0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_waitvblank
	.import		___write_fmtstring
	.export		_main

.segment	"DATA"

_linex:
	.byte	$01
_amanda:
	.addr	L0005
_colors:
	.byte	$05
	.byte	$09
	.byte	$01

.segment	"RODATA"

L0005:
	.byte	$54,$65,$20,$61,$6D,$6F,$20,$41,$6D,$61,$6E,$64,$61,$20,$53,$61
	.byte	$21,$00
L0053:
	.byte	$25,$63,$20,$00

.segment	"BSS"

_x:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     _waitvblank
	lda     #$3F
	sta     $2006
	lda     #$00
	sta     $2006
	lda     #$05
	sta     $2007
	lda     #$3F
	sta     $2006
	lda     #$03
	sta     $2006
	lda     #$01
	sta     $2007
L0026:	lda     #$01
	sta     $4016
	lda     #$00
	sta     $4016
	sta     _x
L0068:	lda     _x
	cmp     #$08
	bcs     L0026
	lda     _amanda
	sta     ptr1
	lda     _amanda+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	beq     L006E
	lda     $4016
	and     #$01
	beq     L006C
	lda     _x
	cmp     #$03
	bne     L006C
	lda     #$20
	sta     $2006
	ldx     #$00
	lda     _linex
	pha
	clc
	adc     #$01
	sta     _linex
	pla
	ldy     #$C0
	jsr     incaxy
	sta     $2006
	lda     #<(L0053)
	ldx     #>(L0053)
	jsr     pushax
	lda     _amanda
	ldx     _amanda+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     _amanda
	stx     _amanda+1
	ldx     #$00
	lda     (regsave,x)
	jsr     pusha0
	ldy     #$04
	jsr     ___write_fmtstring
	jmp     L0026
L006C:	inc     _x
	jmp     L0068
L006E:	sta     $2005
	sta     $2005
	lda     #$08
	sta     $2001
L0067:	jmp     L0067

.endproc

