;
; File generated by cc65 v 2.15 - Git 60958f0
;
	.fopt		compiler,"cc65 v 2.15 - Git 60958f0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_waitvblank
	.import		___ppu_str
	.import		___cbuff
	.import		___wait_key_press_pad1
	.import		___write_string
	.export		_main

.segment	"DATA"

_linex:
	.byte	$01
_amanda:
	.addr	L0006
_colors:
	.byte	$05
	.byte	$09
	.byte	$01

.segment	"RODATA"

L0006:
	.byte	$54,$65,$20,$61,$6D,$6F,$20,$41,$6D,$61,$6E,$64,$61,$20,$53,$61
	.byte	$21,$00

.segment	"BSS"

_x:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     _waitvblank
	lda     #$3F
	sta     $2006
	lda     #$00
	sta     $2006
	lda     #$05
	sta     $2007
	lda     #$3F
	sta     $2006
	lda     #$03
	sta     $2006
	lda     #$01
	sta     $2007
	lda     #$03
	sta     ___cbuff
	jsr     ___wait_key_press_pad1
	lda     #$20
	sta     $2006
	lda     #$85
	sta     $2006
	lda     _amanda
	sta     ___ppu_str
	lda     _amanda+1
	sta     ___ppu_str+1
	jsr     ___write_string
	lda     #$00
	sta     $2005
	sta     $2005
	lda     #$08
	sta     $2001
L004B:	jmp     L004B

.endproc

