;
; File generated by cc65 v 2.15 - Git 60958f0
;
	.fopt		compiler,"cc65 v 2.15 - Git 60958f0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		___ppu_str
	.import		___write_fmtstring
	.export		_func

.segment	"RODATA"

string:
	.byte	'h','i',$00

; ---------------------------------------------------------------
; void __near__ __fastcall__ func (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_func: near

.segment	"CODE"

	lda     #$20
	sta     $2006
	lda     #$C1
	sta     $2006
	lda     #<(string)
	ldx     #>(string)
	jsr     pushax
	lda     #<(___ppu_str)
	ldx     #>(___ppu_str)
	jsr     pushax
	ldy     #$04
	jmp     ___write_string

.endproc

