;
; File generated by cc65 v 2.15 - Git ab1600b
;
	.fopt		compiler,"cc65 v 2.15 - Git ab1600b"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_waitvblank
	.import		_ppu_set_scroll_enable_render
	.import		_write_str
	.import		__ppu_set_cursor_exact
	.import		_joypads
	.import		_update_pad1
	.importzp	_u8_arg
	.export		__test_case
	.export		_main

.segment	"RODATA"

_arr:
	.addr	L0004
L004D:
	.byte	$4E,$4F,$54,$20,$45,$51,$55,$41,$4C,$20,$54,$4F,$20,$31,$30,$00
L0004:
	.byte	$48,$45,$4C,$4C,$4F,$20,$4D,$59,$20,$4C,$49,$42,$21,$00
L0049	:=	L004D+4

; ---------------------------------------------------------------
; void __near__ __fastcall__ _test_case (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__test_case: near

.segment	"CODE"

	lda     _u8_arg
	cmp     #$0A
	bne     L0056
	lda     #$01
	jmp     L0058
L0056:	lda     #$00
L0058:	sta     _u8_arg
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     _waitvblank
	lda     #$3F
	sta     $2006
	lda     #$00
	sta     $2006
	lda     #$01
	sta     $2007
	lda     #$3F
	sta     $2006
	lda     #$03
	sta     $2006
	lda     #$20
	sta     $2007
	tax
	lda     #$21
	jsr     __ppu_set_cursor_exact
	lda     _arr
	ldx     _arr+1
	jsr     _write_str
	ldx     #$20
	lda     #$41
	jsr     __ppu_set_cursor_exact
L003B:	jsr     _update_pad1
	lda     _joypads
	jsr     bnega
	and     #$08
	bne     L003B
	lda     #$0A
	sta     _u8_arg
	jsr     __test_case
	lda     _u8_arg
	beq     L0041
	lda     #<(L0049)
	ldx     #>(L0049)
	jmp     L005A
L0041:	lda     #<(L004D)
	ldx     #>(L004D)
L005A:	jsr     _write_str
	ldx     #$00
	txa
	jsr     _ppu_set_scroll_enable_render
L0059:	jmp     L0059

.endproc

