;
; File generated by cc65 v 2.15 - Git 69fbcb3
;
	.fopt		compiler,"cc65 v 2.15 - Git 69fbcb3"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_waitvblank
	.import		_ppu_set_scroll_enable_render
	.import		_write_str
	.import		__ppu_set_cursor_exact
	.export		_test_case
	.export		_main

.segment	"RODATA"

_arr:
	.addr	L0001
L0001:
	.byte	$48,$45,$4C,$4C,$4F,$20,$4D,$59,$20,$4C,$49,$42,$21,$00
L003B:
	.byte	$4C,$45,$53,$53,$20,$54,$48,$41,$4E,$20,$31,$30,$00
L0037:
	.byte	$4D,$4F,$52,$45,$20,$54,$48,$41,$4E,$20,$31,$30,$00

; ---------------------------------------------------------------
; unsigned char __near__ __fastcall__ test_case (const unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_test_case: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (sp),y
	cmp     #$0B
	tya
	tax
	bcc     L0044
	lda     #$01
	jmp     incsp1
L0044:	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     _waitvblank
	lda     #$3F
	sta     $2006
	lda     #$00
	sta     $2006
	lda     #$01
	sta     $2007
	lda     #$3F
	sta     $2006
	lda     #$03
	sta     $2006
	lda     #$20
	sta     $2007
	tax
	lda     #$21
	jsr     __ppu_set_cursor_exact
	lda     _arr
	ldx     _arr+1
	jsr     _write_str
	ldx     #$20
	lda     #$41
	jsr     __ppu_set_cursor_exact
	lda     #$0B
	jsr     _test_case
	tax
	beq     L0033
	lda     #<(L0037)
	ldx     #>(L0037)
	jmp     L0046
L0033:	lda     #<(L003B)
	ldx     #>(L003B)
L0046:	jsr     _write_str
	ldx     #$00
	txa
	jsr     _ppu_set_scroll_enable_render
L0045:	jmp     L0045

.endproc

